server:
  port: 9090

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url:  jdbc:mysql://umcdb.c8xezlmvz99n.ap-northeast-2.rds.amazonaws.com:3306/SE7 # ??????
    username: umc
    password: chamsaenunjack55
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8??
