server:
  port: 8080

spring:
  application:
    name: bapool

  datasource:
#    url: jdbc:mysql://localhost:3306/bapool
#    username: root
#    password: nabigasalrang33
    url: jdbc:mysql://capstone-db.ckycwawmp50l.ap-northeast-2.rds.amazonaws.com:3306/bapool
    username: admin
    password: bes04172qwer
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8
  sql:
    init:
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


jwt:
  secret-key: c8fjj34ba-1554-48a4-b549-b926f5fedf23

AUTHORIZATION_HEADER: ACCESS-TOKEN