
server:
  port: 9090

spring:
  application:
    name: demo

  datasource:
    platform: mysql
#    url: jdbc:mysql://localhost:3306/testDB
#    username: root
#    password: nabigasalrang33
    url:  jdbc:mysql://umcdb.c8xezlmvz99n.ap-northeast-2.rds.amazonaws.com:3306/SE7
    username: umc
    password: chamsaenunjack55
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8??

  servlet:
    multipart:
      file-size-threshold: 1MB #spring.servlet.multipart.file-size-threshold: 파일이 메모리에 기록되는 임계값 (default: 0B)
      #      location: C:/Temp #spring.servlet.multipart.location: 업로드된 파일의 임시 저장 공간
      max-file-size: 100MB #spring.servlet.multipart.max-file-size: 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB #spring.servlet.multipart.max-request-size: 요청의 최대 사이즈 (default: 10MB)

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      platform: mysql

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.boot.autoconfigure: ERROR

# jwt 관련 설정 추가
#jwt:
#  header: Authorization
#  secret: tkfkddmssmfehakdrktnwmqdmsdkdlcjfja
#  token-validity-in-seconds: 86400