spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
        default_batch_fetch_size: 1000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jenga-db.ctlvmztgkjsi.ap-northeast-2.rds.amazonaws.com:3306/jenga-dev
    username: jenga
    password: jenga1234!

  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  jackson:
    serializaion:
      fail-on-empty-beans: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${/jenga/oauth/kakao/client-id}
            redirect-uri: "http://localhost:8080/api/auth"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, age_range, gender
            client-name: Kakao
          naver:
            client-id: ${/jenga/oauth/naver/client-id}
            client-secret: ${/jenga/oauth/naver/client-secret}
            redirect-uri: "http://localhost:8080/api/auth"
            authorization-grant-type: authorization_code
            scope: nickname, email, age, gender
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

jwt:
  secret: AQICAHiIPZmqcuiBHsP3gjLeeM4tRKuQiAntjhS8v/Dy9LeecgHZ9PyRGfEvyxNvjKT5PJo9AAAA4zCB4AYJKoZIhvcNAQcGoIHSMIHPAgEAMIHJBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLzOxr2U15StoLa9WAIBEICBmzYbALVoA+c4B0cAGvUZRDzl/KSkdnzlF3YgDsB6h6z8N6RUmBTLS5NcHdYxJ/WzkYxkPvteQojHTe0OM6hr03yXo8hLba7loLbf3TpChXoH6oxBoSWDw/amRIw2tyFikIRDgxb7SExf7yeL/dbdHEyuhM6TdXxykLvGbEjaa3SdukV08b32vj0wIhXm0cqbar2NCcfpcTTzvnC0
  access-token-expiry: 86400000 #1?
  refresh-token-expiry: 2592000000 #1?
  access-token-header: Authorization
  refresh-token-header: Refresh-Token

awsParameterStorePropertySource:
  enabled: false
