server:
  port: 8081
  host:
    api: http://localhost:8081

spring:
  application:
    name: scrap
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ENC(d9a6FW0C4hoxeMUmQuVMbyUnRmJbBLKnWmKERPABNsJPg49Lh6N27hZ4XqlaJuc/eHFTawf4zHrQQFu3kzdwf/WAPLqRn5tQ7cH8pa3id+1WnyAr07XRcw==)
    username: ENC(VXpqUaVULnfLfvKtGlN/0g==)
    password: ENC(uhwljWyBiiO7fPcl27j9ai3nky/jEqEQd1RvvzQTDj0=)
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
  # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전

  jpa:
    hibernate:
      ddl-auto: update # create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      platform: mysql
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : 5678

logging.level:
    org.hibernate.type.descriptor.sql: trace

servers:
  - url: https://scrap.hana-umc.shop/
    description: Production server