server:
  port: 8081
  host:
    api: https://scrap.hana-umc.shop

spring:
  application:
    name: scrap
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    platform: mysql
#    url: jdbc:mysql://umcdb.c8xezlmvz99n.ap-northeast-2.rds.amazonaws.com :3306/scrap_local
#    username: umc
#    password: chamsaenunjack55
    url: jdbc:mysql://scrap-db.cwu2l7srgref.ap-northeast-2.rds.amazonaws.com:3306/scrap
    username: scrap
    password: chamsaenunjack55
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
  # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전

  jpa:
    hibernate:
      ddl-auto: update #create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      platform: mysql

logging.level:
  org.hibernate.type.descriptor.sql: trace

servers:
  - url: https://scrap.hana-umc.shop/
    description: Production server

security.jwt.token.secret-key: tempSecretKeyItMustBeChanged